# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hnsw.proto

require "google/protobuf"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("hnsw.proto", syntax: :proto3) do
    add_message "HNSWGraphNode" do
      optional :id, :string, 1
      repeated :vector, :float, 2
      optional :level, :int32, 3
      repeated :neighbors, :string, 4
    end
    add_message "HNSWGraph" do
      optional :entrypoint_id, :string, 1
      optional :max_level, :int32, 2
      optional :similarity_metric, :string, 3
      optional :dimensions, :int32, 4
      optional :m, :int32, 5
      optional :ef, :int32, 6
      repeated :nodes, :message, 7, "HNSWGraphNode"
    end
  end
end

HNSWGraphNode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HNSWGraphNode").msgclass
HNSWGraph = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HNSWGraph").msgclass
